export type Role = "user" | "moderator" | "admin" | "master_admin";

/** Full admin panel access (admin or master administrator). */
export function isAdministrationRole(role: Role): boolean {
  return role === "admin" || role === "master_admin";
}

export type OrderStatus =
  | "draft"
  | "submitted"
  | "under_review"
  | "delivered"
  | "invoiced";

export interface CatalogItem {
  id: string;
  categoryId: string;
  nameBn: string;
  nameEn: string;
}

export interface CategoryDef {
  id: string;
  nameBn: string;
  nameEn: string;
  markupPercent?: number;
  items: CatalogItem[];
}

export interface OrderLine {
  id: string;
  serial: number;
  categoryId: string;
  itemId: string;
  itemNameBn: string;
  itemNameEn: string;
  kg: string;
  gram: string;
  piece: string;
  instructions?: string;
  unitPrice?: number;
  lineTotal?: number;
  /** Set when admin generates billing invoice (DB + API). */
  markupPercent?: number;
  markupAmount?: number;
  unitPriceAfterMarkup?: number | null;
  lineTotalAfterMarkup?: number | null;
  profitLossAmount?: number;
}

export interface Order {
  id: string;
  /** Procurement requester (prototype) */
  ownerId?: string;
  /** Moderator this order is assigned to. */
  assignedModeratorId?: string | null;
  /** User who created this order row (staff or customer self-serve). */
  createdById?: string | null;
  createdByName?: string | null;
  createdByRole?: string | null;
  orderNo: string;
  orderDate: string;
  /** Server/local create timestamp. */
  createdAt?: string;
  /** ISO timestamp when the user confirmed submit (optional on legacy / seed data). */
  submittedAt?: string;
  /** ISO timestamp when delivery was marked complete. */
  deliveredAt?: string;
  deliveryDate: string;
  deliveryTime?: string;
  status: OrderStatus;
  billingAddress: string;
  deliveryAddress: string;
  contactPerson: string;
  phone: string;
  lines: OrderLine[];
  signatureDataUrl?: string | null;
  challanGenerated?: boolean;
  /** Generated by moderator for admin procurement review. */
  purchaseInvoiceGenerated?: boolean;
  /** Who generated the purchase invoice (affects purchase billing cycle/payment attribution). */
  purchaseInvoiceGeneratedBy?: "moderator" | "admin";
  /** Generated by admin for final customer billing. */
  billingInvoiceGenerated?: boolean;
  /** When the active customer billing invoice row was created (API). */
  billingInvoiceCreatedAt?: string | null;
  /** When the active purchase invoice row was created (API). */
  purchaseInvoiceCreatedAt?: string | null;
  /** @deprecated use billingInvoiceGenerated */
  invoiceGenerated?: boolean;
  subtotal?: number;
  purchaseSubtotal?: number;
  billingSubtotal?: number;
  markupPercent?: number;
  /** Category-wise billing markup (%) used when admin generated billing invoice. */
  billingCategoryMarkups?: Record<string, number>;
  grandTotal?: number;
  /** Net billing payments minus billing adjustments (API; matches admin settlement). */
  billingNetPaid?: number;
  /** Remaining customer invoice balance; absent on legacy/local payloads. */
  billingAmountDue?: number | null;
  /** Set when master admin soft-deleted the order on the server. */
  deletedAt?: string | null;
}

export interface SessionUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: Role;
  billingAddress: string;
  deliveryAddress: string;
  /** Whether admin has blocked this account. */
  isActive?: boolean;
  /** ISO timestamp set when the account is created. */
  registeredAt?: string;
  /** ISO timestamp set when an admin soft-deletes the account. */
  deletedAt?: string;
}
